<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="0" failures="1" name="Sage will exist" tests="1" time="0.007080">
<testcase classname="Sage will exist.Sage has a web address that it responds to" name="Sage has a web address that it responds to" time="0.007080">
  <failure message="failed Sage has a web address that it responds to" type="failed">
Scenario: Sage has a web address that it responds to

When I open http://sage.iu.edu
Then I should see "Hello World"

Message:
getaddrinfo: nodename nor servname provided, or not known (SocketError)
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/net/http.rb:560:in `initialize'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/net/http.rb:560:in `open'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/net/http.rb:560:in `connect'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/timeout.rb:53:in `timeout'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/timeout.rb:93:in `timeout'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/net/http.rb:560:in `connect'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/net/http.rb:553:in `do_start'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/net/http.rb:548:in `start'
(eval):2:in `/^I open (.+)$/'
features/Sage_will_exist.feature:8:in `When I open http://sage.iu.edu'  </failure>
</testcase>
</testsuite>
